version: '3.8'

services:

 postgres_db2:
  image: postgres:latest
  container_name: PostgresCont_2 
  restart: no
  environment:
  - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
  - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
  - POSTGRES_DB=${DATABASE_DB_NAME}
  ports:
  - '5432:5432'
  volumes:
  - postgres_db2:/var/lib/postgresql/data

 pgadmin:
  image: dpage/pgadmin4
  container_name: pgadmin_container_new2
  restart: no
  environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  ports:
      - '5050:80'

volumes:
 postgres_db2:
  driver: local

